spring.application.name=masil
# server port
server.port=8087


# Automatic Restart
spring.devtools.restart.enabled=true

# Live Reload
spring.devtools.livereload.enabled=true

# mariaDB
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/masil
spring.datasource.username=masil
spring.datasource.password=1234

# jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

logging.level.org.hibernate.type.descriptor.sql=trace


# 3. ?? ?? ?? ?? (???? ??)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# 4. API ? (??? ????? ??? ????)

api.key=AIzaSyDIz2lnn3WBncblQ6Y6QNYD4nFwvXxzaDI

gemini.model=gemini-3.1-flash-lite-preview




spring.jpa.open-in-view=false